# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kevin/Documents/CS3100/MemoryScheduling

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kevin/Documents/CS3100/MemoryScheduling

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/Documents/CS3100/MemoryScheduling/CMakeFiles /home/kevin/Documents/CS3100/MemoryScheduling/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/Documents/CS3100/MemoryScheduling/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SchedulerSimulator

# Build rule for target.
SchedulerSimulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SchedulerSimulator
.PHONY : SchedulerSimulator

# fast build rule for target.
SchedulerSimulator/fast:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/build
.PHONY : SchedulerSimulator/fast

sources/ASJQueue.o: sources/ASJQueue.cpp.o
.PHONY : sources/ASJQueue.o

# target to build an object file
sources/ASJQueue.cpp.o:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/ASJQueue.cpp.o
.PHONY : sources/ASJQueue.cpp.o

sources/ASJQueue.i: sources/ASJQueue.cpp.i
.PHONY : sources/ASJQueue.i

# target to preprocess a source file
sources/ASJQueue.cpp.i:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/ASJQueue.cpp.i
.PHONY : sources/ASJQueue.cpp.i

sources/ASJQueue.s: sources/ASJQueue.cpp.s
.PHONY : sources/ASJQueue.s

# target to generate assembly for a file
sources/ASJQueue.cpp.s:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/ASJQueue.cpp.s
.PHONY : sources/ASJQueue.cpp.s

sources/Burst.o: sources/Burst.cpp.o
.PHONY : sources/Burst.o

# target to build an object file
sources/Burst.cpp.o:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Burst.cpp.o
.PHONY : sources/Burst.cpp.o

sources/Burst.i: sources/Burst.cpp.i
.PHONY : sources/Burst.i

# target to preprocess a source file
sources/Burst.cpp.i:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Burst.cpp.i
.PHONY : sources/Burst.cpp.i

sources/Burst.s: sources/Burst.cpp.s
.PHONY : sources/Burst.s

# target to generate assembly for a file
sources/Burst.cpp.s:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Burst.cpp.s
.PHONY : sources/Burst.cpp.s

sources/Event.o: sources/Event.cpp.o
.PHONY : sources/Event.o

# target to build an object file
sources/Event.cpp.o:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Event.cpp.o
.PHONY : sources/Event.cpp.o

sources/Event.i: sources/Event.cpp.i
.PHONY : sources/Event.i

# target to preprocess a source file
sources/Event.cpp.i:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Event.cpp.i
.PHONY : sources/Event.cpp.i

sources/Event.s: sources/Event.cpp.s
.PHONY : sources/Event.s

# target to generate assembly for a file
sources/Event.cpp.s:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Event.cpp.s
.PHONY : sources/Event.cpp.s

sources/EventQueue.o: sources/EventQueue.cpp.o
.PHONY : sources/EventQueue.o

# target to build an object file
sources/EventQueue.cpp.o:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/EventQueue.cpp.o
.PHONY : sources/EventQueue.cpp.o

sources/EventQueue.i: sources/EventQueue.cpp.i
.PHONY : sources/EventQueue.i

# target to preprocess a source file
sources/EventQueue.cpp.i:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/EventQueue.cpp.i
.PHONY : sources/EventQueue.cpp.i

sources/EventQueue.s: sources/EventQueue.cpp.s
.PHONY : sources/EventQueue.s

# target to generate assembly for a file
sources/EventQueue.cpp.s:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/EventQueue.cpp.s
.PHONY : sources/EventQueue.cpp.s

sources/IOQueues.o: sources/IOQueues.cpp.o
.PHONY : sources/IOQueues.o

# target to build an object file
sources/IOQueues.cpp.o:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/IOQueues.cpp.o
.PHONY : sources/IOQueues.cpp.o

sources/IOQueues.i: sources/IOQueues.cpp.i
.PHONY : sources/IOQueues.i

# target to preprocess a source file
sources/IOQueues.cpp.i:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/IOQueues.cpp.i
.PHONY : sources/IOQueues.cpp.i

sources/IOQueues.s: sources/IOQueues.cpp.s
.PHONY : sources/IOQueues.s

# target to generate assembly for a file
sources/IOQueues.cpp.s:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/IOQueues.cpp.s
.PHONY : sources/IOQueues.cpp.s

sources/MemManager.o: sources/MemManager.cpp.o
.PHONY : sources/MemManager.o

# target to build an object file
sources/MemManager.cpp.o:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/MemManager.cpp.o
.PHONY : sources/MemManager.cpp.o

sources/MemManager.i: sources/MemManager.cpp.i
.PHONY : sources/MemManager.i

# target to preprocess a source file
sources/MemManager.cpp.i:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/MemManager.cpp.i
.PHONY : sources/MemManager.cpp.i

sources/MemManager.s: sources/MemManager.cpp.s
.PHONY : sources/MemManager.s

# target to generate assembly for a file
sources/MemManager.cpp.s:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/MemManager.cpp.s
.PHONY : sources/MemManager.cpp.s

sources/Processor.o: sources/Processor.cpp.o
.PHONY : sources/Processor.o

# target to build an object file
sources/Processor.cpp.o:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Processor.cpp.o
.PHONY : sources/Processor.cpp.o

sources/Processor.i: sources/Processor.cpp.i
.PHONY : sources/Processor.i

# target to preprocess a source file
sources/Processor.cpp.i:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Processor.cpp.i
.PHONY : sources/Processor.cpp.i

sources/Processor.s: sources/Processor.cpp.s
.PHONY : sources/Processor.s

# target to generate assembly for a file
sources/Processor.cpp.s:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Processor.cpp.s
.PHONY : sources/Processor.cpp.s

sources/RRQueue.o: sources/RRQueue.cpp.o
.PHONY : sources/RRQueue.o

# target to build an object file
sources/RRQueue.cpp.o:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/RRQueue.cpp.o
.PHONY : sources/RRQueue.cpp.o

sources/RRQueue.i: sources/RRQueue.cpp.i
.PHONY : sources/RRQueue.i

# target to preprocess a source file
sources/RRQueue.cpp.i:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/RRQueue.cpp.i
.PHONY : sources/RRQueue.cpp.i

sources/RRQueue.s: sources/RRQueue.cpp.s
.PHONY : sources/RRQueue.s

# target to generate assembly for a file
sources/RRQueue.cpp.s:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/RRQueue.cpp.s
.PHONY : sources/RRQueue.cpp.s

sources/ReadyQueue.o: sources/ReadyQueue.cpp.o
.PHONY : sources/ReadyQueue.o

# target to build an object file
sources/ReadyQueue.cpp.o:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/ReadyQueue.cpp.o
.PHONY : sources/ReadyQueue.cpp.o

sources/ReadyQueue.i: sources/ReadyQueue.cpp.i
.PHONY : sources/ReadyQueue.i

# target to preprocess a source file
sources/ReadyQueue.cpp.i:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/ReadyQueue.cpp.i
.PHONY : sources/ReadyQueue.cpp.i

sources/ReadyQueue.s: sources/ReadyQueue.cpp.s
.PHONY : sources/ReadyQueue.s

# target to generate assembly for a file
sources/ReadyQueue.cpp.s:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/ReadyQueue.cpp.s
.PHONY : sources/ReadyQueue.cpp.s

sources/SJQueue.o: sources/SJQueue.cpp.o
.PHONY : sources/SJQueue.o

# target to build an object file
sources/SJQueue.cpp.o:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/SJQueue.cpp.o
.PHONY : sources/SJQueue.cpp.o

sources/SJQueue.i: sources/SJQueue.cpp.i
.PHONY : sources/SJQueue.i

# target to preprocess a source file
sources/SJQueue.cpp.i:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/SJQueue.cpp.i
.PHONY : sources/SJQueue.cpp.i

sources/SJQueue.s: sources/SJQueue.cpp.s
.PHONY : sources/SJQueue.s

# target to generate assembly for a file
sources/SJQueue.cpp.s:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/SJQueue.cpp.s
.PHONY : sources/SJQueue.cpp.s

sources/Scheduler.o: sources/Scheduler.cpp.o
.PHONY : sources/Scheduler.o

# target to build an object file
sources/Scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Scheduler.cpp.o
.PHONY : sources/Scheduler.cpp.o

sources/Scheduler.i: sources/Scheduler.cpp.i
.PHONY : sources/Scheduler.i

# target to preprocess a source file
sources/Scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Scheduler.cpp.i
.PHONY : sources/Scheduler.cpp.i

sources/Scheduler.s: sources/Scheduler.cpp.s
.PHONY : sources/Scheduler.s

# target to generate assembly for a file
sources/Scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Scheduler.cpp.s
.PHONY : sources/Scheduler.cpp.s

sources/Task.o: sources/Task.cpp.o
.PHONY : sources/Task.o

# target to build an object file
sources/Task.cpp.o:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Task.cpp.o
.PHONY : sources/Task.cpp.o

sources/Task.i: sources/Task.cpp.i
.PHONY : sources/Task.i

# target to preprocess a source file
sources/Task.cpp.i:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Task.cpp.i
.PHONY : sources/Task.cpp.i

sources/Task.s: sources/Task.cpp.s
.PHONY : sources/Task.s

# target to generate assembly for a file
sources/Task.cpp.s:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/Task.cpp.s
.PHONY : sources/Task.cpp.s

sources/main.o: sources/main.cpp.o
.PHONY : sources/main.o

# target to build an object file
sources/main.cpp.o:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/main.cpp.o
.PHONY : sources/main.cpp.o

sources/main.i: sources/main.cpp.i
.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cpp.i:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/main.cpp.i
.PHONY : sources/main.cpp.i

sources/main.s: sources/main.cpp.s
.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cpp.s:
	$(MAKE) -f CMakeFiles/SchedulerSimulator.dir/build.make CMakeFiles/SchedulerSimulator.dir/sources/main.cpp.s
.PHONY : sources/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SchedulerSimulator"
	@echo "... sources/ASJQueue.o"
	@echo "... sources/ASJQueue.i"
	@echo "... sources/ASJQueue.s"
	@echo "... sources/Burst.o"
	@echo "... sources/Burst.i"
	@echo "... sources/Burst.s"
	@echo "... sources/Event.o"
	@echo "... sources/Event.i"
	@echo "... sources/Event.s"
	@echo "... sources/EventQueue.o"
	@echo "... sources/EventQueue.i"
	@echo "... sources/EventQueue.s"
	@echo "... sources/IOQueues.o"
	@echo "... sources/IOQueues.i"
	@echo "... sources/IOQueues.s"
	@echo "... sources/MemManager.o"
	@echo "... sources/MemManager.i"
	@echo "... sources/MemManager.s"
	@echo "... sources/Processor.o"
	@echo "... sources/Processor.i"
	@echo "... sources/Processor.s"
	@echo "... sources/RRQueue.o"
	@echo "... sources/RRQueue.i"
	@echo "... sources/RRQueue.s"
	@echo "... sources/ReadyQueue.o"
	@echo "... sources/ReadyQueue.i"
	@echo "... sources/ReadyQueue.s"
	@echo "... sources/SJQueue.o"
	@echo "... sources/SJQueue.i"
	@echo "... sources/SJQueue.s"
	@echo "... sources/Scheduler.o"
	@echo "... sources/Scheduler.i"
	@echo "... sources/Scheduler.s"
	@echo "... sources/Task.o"
	@echo "... sources/Task.i"
	@echo "... sources/Task.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

